### ISSUE TITLE
Says "Completed" but folder is empty

### ISSUE THREAD

**Issue by tseemann** [enasequence/enaBrowserTools#11]
It seems to indicate success, but there is no data:

```
% ls
<empty folder>

% ./enaDataGet  SRR3319297
Completed

% ls 
SRR3319297

% ls  SRR3319297
<empty folder>
```

**Comment by tseemann** [comment]
Update:

If I run `-f fastq` instead, something happens!
I guess this is because the submitters FASTQ is not always available?
If so, it should fail with an error or warning instead?

```
% ./enaDataGet -f fastq  SRR3319297
Downloading file with md5 check:
ftp.sra.ebi.ac.uk/vol1/fastq/SRR331/007/SRR3319297/SRR3319297_1.fastq.gz
```

PS. i like how you do put it in a folder with the SRR name - that is excellent!

**Comment by tseemann** [comment]
Update - it downloaded R1 but failed on R2:

```
Downloading file with md5 check:ftp.sra.ebi.ac.uk/vol1/fastq/SRR331/007/SRR3319297/SRR3319297_2.fastq.gz
Failed to download file
Completed
linuxbrew@trillian:python $ ls SRR3319297/ -l
total 288056
294965575 Jun 29 11:55 SRR3319297_1.fastq.gz
```

**Comment by nicsilvester** [comment]
Thanks.  Will look into this.  It should give you an error message if it failed.

**Comment by chrisgulvik** [comment]
I tried the identical cmd `./enaDataGet  SRR3319297` and it prints `Completed` but the SRR3319297 dir is empty. This is the same behavior for py2 and py3.

**Comment by nicsilvester** [comment]
There was a problem with the check for number of files > 0.  I forgot that split on a character of an empty string returns a list with an empty string, not an empty list.  Have fixed this and it will be in the next update.
You'll now get the message you should have gotten before that there are no files of that format for the run.
I've also added a check if the run folder is empty and delete if it is so. If you request metadata download, you'll keep the run folder with just the XML

**Comment by nicsilvester** [comment]
Added into latest commit. Will be in next release: v1.3
