### ISSUE TITLE
Make --aspera options an external file

### ISSUE THREAD

**Issue by tseemann** [enasequence/enaBrowserTools#13]
When packaging the tools on a shared system we can't be expected to change the `utils.py` script every time we upgrade.

Can you please read the settings from a file specified in an environmental variable?
And optionally allow the file to be specified with the `--aspera` option?

```
export ENADATAGET_ASPERA_CONFIG=/my/system/path/to/aspera/settings.ini

# or

enaGetData --aspera /my/system/path/to/aspera/settings.ini
```

The `settings.ini` file could be YAML preferably, or JSON or "python" as you have below.

```
If you wish to use Aspera to download read or analysis files, you will need to edit the utils.py script. You will minimally need to specify the location of ascp and the licence file on your computer. All available aspera settings that can be modified are located at the top of utils.py:

ASPERA_BIN = 'ascp' # ascp binary
ASPERA_PRIVATE_KEY = '/path/to/aspera_dsa.openssh' # ascp private key file
ASPERA_LICENSE = 'aspera-license' # ascp license file
ASPERA_OPTIONS = '' # set any extra aspera options
ASPERA_SPEED = '100M' # set aspera download speed
```

**Comment by tseemann** [comment]
Another option that would be good is 
```
enaGetData --aspera "ascp -i /path/to/ssh.pub -m 100M` .....
```

**Comment by nicsilvester** [comment]
Good point thanks.  Will include this in the next update

**Comment by nicsilvester** [comment]
Added in release v1.3.1

Went with option to pass location of file during command:
 --aspera /my/system/path/to/aspera/settings.ini

**Comment by nicsilvester** [comment]
Should also note, chose not to use YAML as we are restricting the code to using only core python packages - excluding any dependency management requirements during installation
