### ISSUE TITLE
sequenceGet.py imports an undefined function

### ISSUE THREAD

**Issue by dorbarker** [enasequence/enaBrowserTools#15]
In `sequenceGet.py`, the function `download_unversioned_wgs()` calls `utils.get_nonversioned_supp_wgs_ftp_url()`. However, this function is undefined in `utils.py`.

**Comment by nicsilvester** [comment]
Thanks for the heads up.  It did exist so it may be a code merge gone wrong.

**Comment by nicsilvester** [comment]
Fixed in release v.1.3.1
