### ISSUE TITLE
Possible bug in report download when selecting a group

### ISSUE THREAD

**Issue by froggleston** [enasequence/enaBrowserTools#2]
Hi there,

When using enaGroupGet, the response that comes back selecting the default format vs fastq results in a different URL between the 'submitted_aspera' and 'fastq_aspera' fields, respectively. For example:

> ./enaGroupGet -f fastq -a PRJEB3008

calls:

> utils.download_report_from_portal()

which results in the following correct response:

`Fetching ERR125556
b'run_accession\tfastq_aspera\tfastq_md5\n'
b'ERR125556\tfasp.sra.ebi.ac.uk:/vol1/fastq/ERR125/ERR125556/ERR125556.fastq.gz\t3568a68dc8e8cdc54c7afa9ae58053cf\n'`

However, when calling:

> ./enaGroupGet -a PRJEB3008

The response, notably the missing colon between fastq_aspera and submitted_aspera, is different:

`Fetching ERR125556
b'run_accession\tsubmitted_aspera\tsubmitted_md5\n'
b'ERR125556\tfasp.sra.ebi.ac.uk/vol1/ERA128/ERA128463/sff/FZU8VVO01_MID9.sff\tbeb7f366441984e0f5f2ada5e57464a6\n'`

Is this a bug? Aspera will fail if I try to use the submitted_aspera link with no colon between the host and the file path.

Cheers,

Rob

**Comment by nicsilvester** [comment]
Thanks for pointing this out.  We'll update the API to add the colon between host and file path.

**Comment by nicsilvester** [comment]
API has been fixed for submitted_aspera field
