### ISSUE TITLE
Aspera option improvement

### ISSUE THREAD

**Issue by tseemann** [enasequence/enaBrowserTools#20]
Thanks for adding the --aspera option, but is very inconvient for all the users on a cluster to have to specify it, as you say "You will need to provide a path to this file every time you chose to run aspera."

Can you make the default be a file specified in an ENV variable?

For example
```
export ENA_ASPERA_COMMANDLINE="-m 300m -i key.ssh -DT" 
#and/or
export ENA_ASPERIA_INIFILE="/bio/sw/enaBrowserTools/etc/aspera.ini"
```

If either of these are set, you use them. But let -a override it.

**Comment by chrisgulvik** [comment]
os.environ.get() works the same in both py2 and py3 and the getattr() approach should as well.

If the aspera_settings.ini file is always going to be ../ from `enaDataGet.py` and `utils.py` and you wanted to save that full path as a place to check when a specific file isn't provided and env var unset, you could put a line inside utils.py `enaBrowserTools_path = os.path.dirname(os.path.dirname(__file__))` then call on the utils module to get it.

Extend this if-statement: https://github.com/enasequence/enaBrowserTools/blob/c0911deb23679d8c25723c4fdedb85451df11810/python3/enaDataGet.py#L53-L55
```
elif os.environ.get('ENA_ASPERA_INIFILE'):
    aspera = True
    utils.set_aspera_variables(os.environ.get('ENA_ASPERA_INIFILE'))
elif:
    eBT_path = getattr(utils, 'enaBrowserTools_path', '')
    if os.path.exists(os.path.join(eBT_path, 'aspera_settings.ini')):
        aspera = True
        utils.set_aspera_variables(os.path.join(eBT_path, 'aspera_settings.ini'))
```

**Comment by nicsilvester** [comment]
I'l have a look at this.  I usually try to avoid environment variables as they can be dangerous. Though given these scripts are run locally I can probably loosen that rule

**Comment by nicsilvester** [comment]
Added in v1.4 release.
