### ISSUE TITLE
ASPERA_LICENSE hard-coded?

### ISSUE THREAD

**Issue by tseemann** [enasequence/enaBrowserTools#22]
I notice also the code refers to `ASPERA_LICENSE` and `os.path.exists(ASPERA_LICENSE)`. 

I don't have this file, I use this `ascp` installation on the command line:
http://download.asperasoft.com/download/sw/connect/3.6.2/aspera-connect-3.6.2.117442-linux-64.tar.gz

SO

I've upgraded my package to support 3.7.2 now using: https://download.asperasoft.com/download/sw/cli/3.7.2/aspera-cli-3.7.2.354.010c3b8-linux-64-release.sh

It seems to have `/home/linuxbrew/.linuxbrew/etc/aspera-license` file, so I assume adding `ASPERA_LICENSE` to the `--aspera FILE.INI` will work?

**Comment by nicsilvester** [comment]
I think this is tied up with issue 21. My current thought without the code in front of me is that in one (python) version of the code I removed the wrong line(s). I'll aim to release a minor update with this fix today

**Comment by nicsilvester** [comment]
fixed in v1.3.2
