### ISSUE TITLE
Download by GCA accession

### ISSUE THREAD

**Issue by AntonPetrov** [enasequence/enaBrowserTools#23]
Is it possible to use this software to download all sequences associated with a _GCA_ accession, for example [GCA_000009045.1](http://www.ebi.ac.uk/ena/data/view/GCA_000009045.1)? This would be very helpful for our work on Rfam.

**Comment by nicsilvester** [comment]
Yes. You use enaDataGet with the GCA accession. You will need to use the WGS flag if you want to download the WGS set with the rest of the sequences and you need to state which format you want: fasta or embl (flat file).

Currently there is one limitation in that it will download the latest version of a sequence, not necessarily the version the assembly requires. This will usually only be an issue for users requiring an earlier assembly version. This is a limitation in the ENA browser that we are working to fix.

**Comment by AntonPetrov** [comment]
Thank you for a quick reply @nicsilvester! I tried downloading several _GCA_ accessions and everything worked fine so I will close this issue.
