### ISSUE TITLE
Confusion in WGS vs Assembly

### ISSUE THREAD

**Issue by jjkoehorst** [enasequence/enaBrowserTools#29]
I am a bit confused by the usage of WGS vs Assembly.

My assumption was that all genomes that are assembled and "annotated" / available in the EMBL format could be retrieved through

    ./enaGroupGet -g wgs -f embl -d ../../ENA/ --wgs --meta --index --subtree 2

In this case this would be **Whole Genome Sequencing** under taxon group 2.

But then what does the following do? 

    ./enaGroupGet --meta --index --subtree 2 -f embl -g assembly --wgs

It now downloads GCA_00000 genomes which are as I can see so far drafts and when diving into the file the header contains `ABFD02000031` which corresponds to a genome `ABFD02` that is available through the first command.

However it does download some extra files which contains the assembly information. Is that the major difference between `-g wgs and -g assembly` ? Or will some genomes be available through -g assembly and not by -g wgs?

**Comment by nicsilvester** [comment]
WGS will include only WGS sets.
Assembly will include only assemblies submitted to the genome collections (those with GCA_ accessions).

Not all assemblies contain WGS sets. I believe that all WGS sets should be included in the assembly group but this may not be true for older WGS sets.

When downloading an assembly with the wgs flag, you will get the following files where such sequences exist within the assembly:
1.  The WGS set 
2.  The set of chromosomes
3.  The set of unlocalised sequences (sequences that have been associated with a specific chromosome but have not been ordered or oriented on the chromosome)
4.  The set of unplaced sequences (sequences that have not been associated with a specific chromosome).
5.  The sequence report summarising the sequences in (2-4)

Originally we excluded all WGS sequences from the unplaced list, however this policy was changed after WGS sets started containing scaffolds as well as contigs. If an assembly consists solely of a WGS set, you will only get file (1).
