### ISSUE TITLE
Some of the .py scripts are still 'executable'

### ISSUE THREAD

**Issue by tseemann** [enasequence/enaBrowserTools#3]
Need to `chmod -x *.py` as they aren't directly runnable (no `#!` line).

**Comment by nicsilvester** [comment]
Thanks for bringing this to our attention.  Originally the scripts were to be directly runnable but the decision was made against this so we didn't have to worry about the location of the python installation on the local computers.  Looks like I forgot to change the file permissions when I removed the `#!` line.
We'll make this change in the next commit.

**Comment by tseemann** [comment]
Thank you.

**Comment by nicsilvester** [comment]
Added into latest commit. Will be in next release: v1.3
