### ISSUE TITLE
Download WGS set in absence of higher level identifiers in the GCA xml

### ISSUE THREAD

**Issue by kalvari** [enasequence/enaBrowserTools#31]
I'm suggesting this as an enhancement of the [enaDataGet](https://github.com/enasequence/enaBrowserTools/blob/master/python/enaDataGet.py) tool. 

For example [GCA_001005085.2](https://www.ebi.ac.uk/ena/data/view/GCA_001005085.2). In cases such as this, the tool will only download the assembly [xml](https://www.ebi.ac.uk/ena/data/view/GCA_001005085.2&display=xml) file. It would be very helpful if the tool downloaded the WGS set directly without having to use *-w* option as an additional step. A message for logging purposes would be very handy as well.

**Comment by nicsilvester** [comment]
Added in v1.5 release
