### ISSUE TITLE
Download of paired-end reads fails in python 2.7

### ISSUE THREAD

**Issue by mzganec** [enasequence/enaBrowserTools#33]
Running `enaBrowserTools/python/enaDataGet -f fastq SRR2124780` fails with
```
Downloading file with md5 check:ftp.sra.ebi.ac.uk/vol1/fastq/SRR212/000/SRR2124780/SRR2124780_1.fastq.gz
Downloading file with md5 check:ftp.sra.ebi.ac.uk/vol1/fastq/SRR212/000/SRR2124780/SRR2124780_2.fastq.gz
Error with FTP transfer: [Errno ftp error] 200 Switching to Binary mode.
Downloading file with md5 check:ftp.sra.ebi.ac.uk/vol1/fastq/SRR212/000/SRR2124780/SRR2124780_2.fastq.gz
Error with FTP transfer: [Errno ftp error] 200 Switching to Binary mode.
Failed to download file after two attempts
Completed
```
likely due to [this bug](https://bugs.python.org/issue1067702) in `urllib`. Forward reads are downloaded correctly but the reverse reads are not. Running the same command again downloads reverse reads as well.

The error occurs in python 2.7.12 which ships with Ubuntu 17.10, and python 2.7.14 which comes with Fedora 27. The equivalent python 3 command `enaBrowserTools/python3/enaDataGet -f fastq SRR2124780` works correctly.

**Comment by nicsilvester** [comment]
Thanks for the heads up. This might be a good reason to stop trying to support python 2.7 and switch to just python 3.
I do however have an update that is part completed that will stop the re-download of a file already existing at the download location. I'm hoping to have time before the end of the month to finish and release it.

**Comment by nicsilvester** [comment]
v1.5 contains the check to not re-download files that already exist in the local directory.
Closing this ticket as we can't currently address Python 2.7 issues outside of stopping support for it entirely - not something we can easily do due to the large number of servers that only over 2.7
