### ISSUE TITLE
Failing to connect to sequence read database/server

### ISSUE THREAD

**Issue by jwasmuth** [enasequence/enaBrowserTools#37]
I'm using enaDataGet (1.5) and have been for a while. As of yesterday, I cannot access the short read sets. A typical command is:

enaDataGet -f fastq -a ERR536833

I am able to download genome assemblies. I'm not sure why sequence reads is failing. Is there a server issue for these data or am I doing something wrong?

Thanks for your help

James

**Comment by suranjayathilaka** [comment]
Hi James,

Thanks for reporting this. It's an issue in one of the backend services and will be rectified EOD today.

Suran

**Comment by suranjayathilaka** [comment]
Hi James, 

I've made an update to the utils.py files that resolves this issue (release 1.5.2). Please update your checkout and try again.

Thanks!
Suran
