### ISSUE TITLE
ASERA_BIN detection broken on mac/python3.6.5

### ISSUE THREAD

**Issue by swingingsimian** [enasequence/enaBrowserTools#38]
I cannot get the enaData/GroupGet apps to recognise my local ascp client.

```
$ enaDataGet -as ./aspera_settings.ini SRR6682864
Aspera binary ("/Users/nathanjohnson/Applications/Aspera_CLI/bin/ascp") does not exist. Defaulting to FTP transfer

$ ls /Users/nathanjohnson/Applications/Aspera_CLI/bin/ascp
/Users/nathanjohnson/Applications/Aspera_CLI/bin/ascp
```

Note: I have replaced 'Aspera\ CLI' with 'Aspera_CLI' here.

Digging deeper I find some odd behaviour in the utils.py module:

```
$ python
Python 3.6.5 (default, Apr 25 2018, 14:23:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from python3.utils import set_aspera_variables
>>> set_aspera_variables('aspera_settings.ini')
Aspera binary ("/Users/nathanjohnson/Applications/Aspera_CLI/bin/ascp") does not exist. Defaulting to FTP transfer
False
>>> ASPERA_BIN="/Users/nathanjohnson/Applications/Aspera_CLI/bin/ascp"
>>> if not os.path.exists(ASPERA_BIN):
...     print('Aspera binary ({0}) does not exist. Defaulting to FTP transfer'.format(ASPERA_BIN))
...
>>>
```

Thanks

**Comment by nicsilvester** [comment]
I've completely reworked the Aspera check and use in a new update that I haven't released yet. I'm running a little late on the release but it should be available by the end of the week.

**Comment by nicsilvester** [comment]
Sorry, the rework I was thinking of was added in the May release - I'd mixed up what was waiting for the next one. Looking at what you have pasted above, the double quotes around the path name suggest that you have used them in the settings file. You shouldn't be using quotes in the settings file.

For example, that line of your file should read:
ASPERA_BIN = /Users/nathanjohnson/Applications/Aspera_CLI/bin/ascp

I suspect your file reads:
ASPERA_BIN = "/Users/nathanjohnson/Applications/Aspera_CLI/bin/ascp"

However, I will add a step to strip any double quotes off entries in case any one else makes this mistake. Hope this helps

**Comment by nicsilvester** [comment]
Double quote removal added into version 1.5.4
