### ISSUE TITLE
The `dirname $0` trick fails when symlinks are used

### ISSUE THREAD

**Issue by tseemann** [enasequence/enaBrowserTools#4]
```
#!/bin/bash
dir=`dirname "$0"`
python ${dir}/assemblyGet.py "$@"
```

If this shell script has been symlinked into `/usr/local/bin` say, it won't resolve to the proper place to find the python script.

Use `realpath "$0"` or `readlink -e "$0"` instead.

Or just make the python script directly runnable?

**Comment by nicsilvester** [comment]
Thanks for this.  We had anticipated that users would alias the command, thus keeping running all the files from a single directory location, so hadn't considered symlinks.  We'll make the update in the next code commit.
The decision was made not to make the python scripts directly runnable so we didn't have to deal with the differences in where and how users installed python. The bash location is much more universal.

**Comment by tseemann** [comment]
Another way people do what you want is to use
```
import os, sys
os.path.abspath(os.path.dirname(sys.argv[0]))
```
to locate the location of the script and set the library path import folder from it at runtime.

**Comment by nicsilvester** [comment]
Added into latest commit. Will be in next release: v1.3
