### ISSUE TITLE
Aspera installation hints

### ISSUE THREAD

**Issue by bewt85** [enasequence/enaBrowserTools#40]
Is it possible for you to give some hints on installing Aspera?

I tried install it on a linux server during the workshop today and I think they're no-longer bundling the SSH key we need to supply.

Suran said he'd have a look as part of a ticket but I think https://github.com/enasequence/enaBrowserTools/issues/38 refers to a slightly different issue.

If you do find a way to get this working, it would be really great if you could include some hints in the README or in the wiki.  I'd like to start doing lots of downloading next week and it's going to be loads slower over FTP :(

Thank you for a good session today.

**Comment by swingingsimian** [comment]
This may help:
https://download.asperasoft.com/download/docs/ascp/3.5.2/html/dita/creating_public_key.html

**Comment by nicsilvester** [comment]
Just double checking, are you installing the aspera client or aspera connect? It isn't obvious by the Aspera download page which one you need. Aspera connect should have the key created with installation but the client won't (and comes with other requirements).

**Comment by bewt85** [comment]
Thank you both. I'll need to double check when I'm back on my laptop but I was trying to install on a server and I ended up trying two different deb packages. I remember doing it before and it stuck a certificate in my home directory but it didn't do so this time. Ill have another go though.

That said, does this mean that I can access (public) ENA data using any SSH key (ie it's ignored)?

**Comment by bewt85** [comment]
Sorry for the fuss, it worked fine today.  I _think_ the problem was that I tried to install the wrong thing yesterday and then tried to install the right thing over the top of it and both I and the server got confused.  I started from a fresh machine today and it went fine.

For reverence I:
* went to the [aspera download page](https://downloads.asperasoft.com/)
* clicked 'aspera cli'
* selected the [linux download](https://download.asperasoft.com/download/sw/cli/3.9.0/ibm-aspera-cli-3.9.0.1326.6985b21-linux-64-release.sh)
* ran the bash script (`sudo bash ibm-aspera-cli-3.9.0.1326.6985b21-linux-64-release.sh`)
* added ascp to my PATH (`export PATH=/home/ben/.aspera/cli/bin:$PATH`)

I then tested the install with:
```
ascp -L - -l 300m -P33001 -i ${HOME}/.aspera/cli/etc/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR015/ERR015599/ERR015599_1.fastq.gz /tmp/ERR015599_1.fastq.gz
```

Apologies again and thanks to @swingingsimian and @nicsilvester for their prompt help

**Comment by nicsilvester** [comment]
Thanks for updating with what you have done to get it working for you. We haven't previously put aspera installation hints in this project as that has often been covered by the main ENA site, and of course aspera. The problem is also that aspera changes things often enough that we would struggle to keep up with the hints. I think it best to leave it as is for now, and revisit if there are more regular problems.
