### ISSUE TITLE
Some SRA accession numbers don't work.

### ISSUE THREAD

**Issue by rpolicastro** [enasequence/enaBrowserTools#48]
Hi all,

enaDataGet fails to recognize certain SRA accession numbers. For example, 'SRR10704240' results in an invalid SRA accession number error after using the command `enaDataGet -f fastq  SRR10704240`. However, the experiment accession number, 'SRX7388391', does work with that command.

This is with version 1.5.3.

Cheers!

**Comment by jjkoehorst** [comment]
This also seems to be the case with EMBL / FASTA files. For example

```
python3 enaBrowserTools/python3/enaDataGet.py -f embl -exp -d GCA_004875785.1 GCA_004875785.1
Checking availability of https://www.ebi.ac.uk/ena/browser/api/embl/GCA_004875785.1
ERROR: Record does not exist or is not available for accession provided
```

Should be able to obtain the fasta or embl file from that virus. The ENA page of GCA_004875785.1 also mentions that a contig is available with identifier JF974300.1 but accessing that directly also results in an issue

```
python3 enaBrowserTools/python3/enaDataGet.py -f embl -exp -d JF974300.1 JF974300.1          
Checking availability of https://www.ebi.ac.uk/ena/browser/api/embl/JF974300.1
Error downloading read record: HTTP Error 400: 
Unable to fetch file for JF974300.1, format embl
Completed
```

Attempting to download the fasta file also does not work

```
python3 enaBrowserTools/python3/enaDataGet.py -f fasta -exp -d JF974300.1 JF974300.1
Checking availability of https://www.ebi.ac.uk/ena/browser/api/fasta/JF974300.1
Error downloading read record: HTTP Error 400: 
Unable to fetch file for JF974300.1, format fasta
Completed
```

**Comment by rpolicastro** [comment]
For anyone that may be having the same problem, I found in their code that they are [checking for accession numbers with a maximum of 7 digits](run_pattern = re.compile('^[EDS]RR[0-9]{6,7}$')). However, newer entries can have at least 8 digits. I've initiated a [pull request](https://github.com/enasequence/enaBrowserTools/pull/52) to fix this problem.
