### ISSUE TITLE
Error messages to stderr instead of stdout

### ISSUE THREAD

**Issue by chrisgulvik** [enasequence/enaBrowserTools#5]
This is terrific you've made these available, so thank you for doing that!

It's more of a stylistic request to have error messages go to stderr rather than stdout.

In most scripts you already have the sys module imported, so you could just change the print statements to `sys.stderr.write('ERROR:  <msg> \n')` but you would have to add that `import sys` line into the utils.py in order to change out the `print_error()` function: https://github.com/enasequence/enaBrowserTools/blob/master/python3/utils.py#L485-L487

**Comment by tseemann** [comment]
Yes, all errors and warnings should go to STDERR.

See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4076505/

**Comment by nicsilvester** [comment]
Thanks.  Good point and something I usually follow.  Not sure why I didn't that day.  Will add this fix to the next commit

**Comment by nicsilvester** [comment]
Added into latest commit. Will be in next release: v1.3
