### ISSUE TITLE
TimeoutError with whatever I want to download

### ISSUE THREAD

**Issue by jjkoehorst** [enasequence/enaBrowserTools#62]
I was receiving timeout errors when downloading EMBL files but now I basically get them for any kind of file I want to download. 

```
fastq ERP020473
Checking availability of https://www.ebi.ac.uk/ena/browser/api/xml/ERP020473
Fetching ERR1750995
Downloading file with md5 check:ftp.sra.ebi.ac.uk/vol1/fastq/ERR175/005/ERR1750995/ERR1750995_1.fastq.gz
Error with FTP transfer: <urlopen error ftp error: TimeoutError(110, 'Connection timed out')>
```

any idea what is happening here?

**Comment by lilim-ebi** [comment]
Hi,

Are you still experiencing this problem? There have been some updates since then, so hopefully it should be working.
