### ISSUE TITLE
Error when downloading raw sequencing files from a registered project.

### ISSUE THREAD

**Issue by padpadpadpad** [enasequence/enaBrowserTools#65]
Hi ENA team

I am trying to download all the sequences from this [project](https://www.ebi.ac.uk/ena/browser/view/PRJEB47945?show=reads). Its project accession code is PRJEB47945.

To do this I use the code:

```
enaGroupGet -d ena_test -f fastq -g read PRJEB47945
```

Some of the files do download, but lots of the files give the following error:

```
Fetching ERR7017432
Downloading file with md5 check:ftp.sra.ebi.ac.uk/vol1/fastq/ERR701/002/ERR7017432/ERR7017432_1.fastq.gz
Downloading file with md5 check:ftp.sra.ebi.ac.uk/vol1/fastq/ERR701/002/ERR7017432/ERR7017432_2.fastq.gz
Error with FTP transfer occurred for file: ERR7017431_2.fastq.gzError with FTP transfer: <urlopen error ftp error: error_perm('550 Failed to change directory.')>
Downloading file with md5 check:ftp.sra.ebi.ac.uk/vol1/fastq/ERR701/002/ERR7017432/ERR7017432_2.fastq.gz
Error with FTP transfer occurred for file: ERR7017432_2.fastq.gzError with FTP transfer: <urlopen error ftp error: error_perm('550 Failed to change directory.')>
Failed to download file after two attempts
```

The output is from one sample where the forward read did download but the reverse read did not.

Any idea how to fix the `Error with FTP transfer: <urlopen error ftp error: error_perm('550 Failed to change directory.')>`

Many thanks
Dan

**Comment by lilim-ebi** [comment]
Hi,

Are you still experiencing this problem? It works fine for me, I'm using version 1.5.4.
