### ISSUE TITLE
Accession not found even though it exists

### ISSUE THREAD

**Issue by Jigyasa3** [enasequence/enaBrowserTools#68]
Hey all,

I am using the python version of enaDataGet for downloading the fastq files corresponding to an accession id (that does exist-https://www.ebi.ac.uk/ena/browser/view/ERA3035662?show=reads), but I keep getting an error that `ERROR: Invalid accession provided`

Code used-
`./enaDataGet --format fastq SAMEA7499160`
or
`./enaDataGet --format fastq ERX4643323`

I am using python/3.5.2 and running on an HPC cluster.

Looking forward to suggestions!

**Comment by kairilove09** [comment]
Did you try using enaGroupGet with these accession codes?

**Comment by Manishemblebi** [comment]
Hi @Jigyasa3 ,

Can you please confirm if you are getting the same error for both the command. I can download the fastq files using your second command -./enaDataGet --format fastq ERX4643323.
Can you please check  SSL configuration if  error related to SSL ( please check README.md). 
We had issue with FTP server and should work now. Please try again.
 
I am able to reproduce the ERROR: Invalid accession provided for "./enaDataGet --format fastq SAMEA7499160" command.  There is and issue on verifying the accession. I will fix and push the changes.

**Comment by Jigyasa3** [comment]
Hi @Manishemblebi ,

Sorry, I forgot to reply! The enaDataGet command works perfectly! I am using the bio project id and do not get an error.
code-`/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet --group read --format fastq PRJEB41002`
Thank you!
