### ISSUE TITLE
Consider merging all tools into one tool

### ISSUE THREAD

**Issue by tseemann** [enasequence/enaBrowserTools#7]
Currently you have
```
analysisGet     assemblyGet     enaDataGet     enaGroupGet     readGet     sequenceGet
```

I think it would be much better to have a single executable tool `ena-get` (or similar) where the type of object could specified (or auto-predicted) ?   Or use subcommands like `samtools` and other modern tools. (Note that `argparse` supports sub-commands.)

Is this possible?

**Comment by nicsilvester** [comment]
You only need enaDataGet and enaGroupGet.  The others were left from when it was being built, but yes we can remove the main method from them. 
For now enaDataGet and enaGroupGet still need to be kept separate to keep the command line usage as simple as possible.  We can revisit subcommands later

**Comment by tseemann** [comment]
If they aren't needed they should be removed, or turned into modules, or at least made non-executable?

We are attempting to package this into Homebrew.

**Comment by tseemann** [comment]
Ok, i see you have fixed this now. Thank you.
