### ISSUE TITLE
Call "python3" instead of python for the python3 scripts

### ISSUE THREAD

**Issue by tseemann** [enasequence/enaBrowserTools#8]
Many of us have py2 and py3 co-installed.  In these cases the py2 exe is `python` and the py3 exe is `python3`.

You use `python` for both, which clashes.

**Comment by nicsilvester** [comment]
Thanks for the comment.  I have it installed that way too, but thought that the majority of users would have one or the other installed and wasn't sure if it would be safe to use the "python3" command. I'll update the code and wait and see

**Comment by nicsilvester** [comment]
Added into latest commit. Will be in next release: v1.3
